adding PIGroups to user management display
UnityHPC/unity-web-portal pull request #31
Opened 2022-10-20 20:50 UTC by mckeags7

2022-10-31 19:09 UTC, hakasapl commented
Suggestion:
```
$cur_user_groups = $user->getGroups()
foreach ($cur_user groups as $cur_group) {
echo "<a href='mailto:" . $cur_group->getOwner()->getMail() . "'>" . $cur_group->getPIUID() . "</a>";
}
```

2022-11-09 21:14 UTC, hakasapl requested changes
Some really small readability changes, otherwise the code looks good!

2022-11-09 21:14 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +        }
```suggestion
            }
```
Really small change, just make sure these brackets line up with each other

2022-11-09 21:14 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +
```suggestion

```

2022-11-09 21:14 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +
```suggestion

```

2022-11-14 15:59 UTC, hakasapl requested changes
This should be the last of the syntax fixes, once these are fixed we should be all set

2022-11-14 15:59 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +        }
Small indenting fix

```suggestion
        foreach($cur_user_groups as $cur_group) {
            echo "<a href='mailto:" . $cur_group->getOwner()->getMail() . "'>" . $cur_group->getPIUID() . "</a>";
            if ($cur_group !== array_key_last($cur_user_groups)) {
                echo '<br>';
            }
        }
```

2022-11-14 15:59 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +        echo "<td><a href ='mailto:" . $user->getMail() . "'>" . $user->getMail() . "</a></td>";
Getting rid of extra space on the a tag

```suggestion
        echo "<td><a href='mailto:" . $user->getMail() . "'>" . $user->getMail() . "</a></td>";
```

2022-11-14 15:59 UTC, hakasapl commented on webroot/admin/user-mgmt.php
> +
Remove this line since it adds nothing

```suggestion

```

2022-11-15 18:41 UTC, mckeags7 reviewed
approved changes

2022-11-15 18:46 UTC, mckeags7 reviewed
approved changes

2022-11-16 15:54 UTC, hakasapl approved these changes
Looks good to me!

2022-11-16 15:55 UTC, merged